function drawanalyse(im1g,im2g,ptsd,ptstc,idmaxinlier,idptsmaxitl)
drawmatchdesvector(im1g,im2g,ptsd{1},ptsd{2},0);
title([int2str(size(ptsd{1},1)) '<->'...
    int2str(size(ptsd{2},1)) ' of vectors']);
drawmatchdesvector(im1g,im2g,ptstc{1},ptstc{2},1);
title([int2str(size(ptstc{1},1)) '<->'...
    int2str(size(ptstc{2},1)) ' of tentative correspondences']);
drawmatchdesvector(im1g,im2g,...
    ptstc{1}(idmaxinlier,:),ptstc{2}(idmaxinlier,:),1);
title([int2str(length(idmaxinlier)) '<->'...
    int2str(length(idmaxinlier)) ' of inliers']);
drawmatchdesvector(im1g,im2g,...
    ptstc{1}(idptsmaxitl,:),ptstc{2}(idptsmaxitl,:),1);
title('4 couples initial');